### ISSUE TITLE
test_musicc.py normalization

### ISSUE THREAD

**Issue by EllieYin567** [omanor/MUSiCC#10]
I am trying to run test_musicc.py, and noticed that you could define 
-n, --normalize: Apply MUSiCC normalization (default: false)
However, if I only want to "correct inter-sample variation" not "intra sample". Where should I define this in the command? Thanks much!

**Comment by engal** [comment]
The "-n" option is what you would use for correcting inter-sample variation, the standard MUSiCC normalization process. For intra-sample variation correction, you would use one of the "-c" options, which either uses a default model, or learns a model for each sample, to correct abundances within each sample individually.

Hope that helps!

**Comment by EllieYin567** [comment]
Thank you, Engal! That is super helpful!
