### ISSUE TITLE
learn_lasso_model fails for blank samples with no USCG counts

### ISSUE THREAD

**Issue by prihoda** [omanor/MUSiCC#11]
Hi, I came across an issue when trying to normalize a matrix where a sample (e.g. blank control) contains no USCG counts. 

This means that the mean sample abundance is zero which makes the response just NaNs. Then, the sklearn training fails with `ValueError: cannot convert float NaN to integer`.

Should the response column also be all zeros in this case? Or should an error be thrown? 

Relevant line of code:
https://github.com/borenstein-lab/MUSiCC/blob/478c9244cf406935e67abdf7622bdb05421ab1fb/musicc/core.py#L344

**Comment by prihoda** [comment]
Also begs the question how `min_correction_uscg` and `max_correction_uscg` should be handled in that case.

**Comment by engal** [comment]
Hi,

Thanks for your question, hopefully I can help.

MUSiCC is not meant to be used on samples without any USCGs present (your blank control for example). We do not currently have a good rationale for how to define the average copy number of a gene when there are no genomes present in a sample, and so I think being undefined/NaN is reasonable behavior.

Regarding the behavior when learning sample-specific models, we think that throwing an error is the correct response here, though you have brought up a good point that the error could be more informative. I'll work on an update to check for samples without USCGs prior to model learning and provide the user with a more informative error message, including identifying the samples in question so they can remove them.

Hope that helps!

Best,
Alex

**Comment by prihoda** [comment]
Sounds great, thanks @engal.
