### ISSUE TITLE
core.py error

### ISSUE THREAD

**Issue by cwzkevin** [omanor/MUSiCC#3]
From http://scikit-learn.org/stable/modules/classes.html, it shows the ConvergenceWarning is under Exceptions instead of utils.

Need to change something below in the core.py to pass the test_musicc.py

#from sklearn.utils import ConvergenceWarning
from sklearn.exceptions import ConvergenceWarning

**Comment by gavinmdouglas** [comment]
I ran into this same problem, but it was revolved when I used an earlier version of scikit-learn.

**Comment by Microbiology** [comment]
I ran into the same problem using the installation from `pip`. I just changed the line to `sklearn.exceptions` from `sklearn.utils` in the module file `core.py` and now it seems to be working okay with the other up-to-date modules.

**Comment by engal** [comment]
I just released an update that should address this issue.
