### ISSUE TITLE
Unable to import musicc.core using sklearn 0.20.0

### ISSUE THREAD

**Issue by dchandran** [omanor/MUSiCC#5]
sklearn appears to have changed its module structure. I am able to import musicc.core by changing the import lines at the top of core.py to the following: 
```
from sklearn.model_selection import cross_validate as cross_validation
from sklearn.linear_model import LinearRegression as linear_model  # for the LASSO
from sklearn.exceptions import ConvergenceWarning
```

**Comment by engal** [comment]
Hi,

This issue should be resolved as of MUSiCC version 1.0.3, which addressed deprecated scikit-learn usages.

Thanks for your interest in MUSiCC!
